apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-monitor
  template:
    metadata:
      labels:
        app: k8s-monitor
    spec:
      containers:
      - name: k8s-monitor
        image: k8s-monitor:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-monitor
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: k8s-monitor
