name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true

    - name: Build
      run: |
        GOOS=linux GOARCH=amd64 go build -o k8s-monitor-linux-amd64 ./cmd/server/main.go
        GOOS=linux GOARCH=arm64 go build -o k8s-monitor-linux-arm64 ./cmd/server/main.go
        GOOS=darwin GOARCH=amd64 go build -o k8s-monitor-darwin-amd64 ./cmd/server/main.go
        GOOS=darwin GOARCH=arm64 go build -o k8s-monitor-darwin-arm64 ./cmd/server/main.go

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          k8s-monitor-linux-amd64
          k8s-monitor-linux-arm64
          k8s-monitor-darwin-amd64
          k8s-monitor-darwin-arm64
